### PR TITLE
Memes

### PR DESCRIPTION
**Pull request by akasarx**
-Respring Bug - makes it alot easier to debug the app rather than reboot every time.
-Credit to @coffeebreakerz or whoever made this bug idk

### CODE REVIEW

**Comment by iabem97** [comment]
2 reasons why I'm not accepting this:
- Memes. no, just no.
- a respring won't do. we're dealing with kernel panics here.

**Comment by akasarx** [comment]
1. Yes
2. try it yourself, it actually lets the triple_fetch start again :)

**Comment by Koizum1** [comment]
No, triple_fetch deals with launchd. Not springboard.

**Comment by akasarx** [comment]
Wrong. triple_fetch has to gain the correct port first. Respringing allows this to restart when it stops.

**Comment by coffeebreakerz** [comment]
Triple fetch will not work correctly by just a respring that's true. Commits are meant to describe your actions. I know it is fun to joke a bit, but please keep commits strictly professional to keep a good overview of contributions.
Still i find your creativity a great ability and eventhough the respring bug does not contribute to stability or usability of this jailbreak I still would like to thank you for helping.
I wish people like you wouldn't receive such bad credit.

**Pull request closed without merging**
