### PR TITLE
iPhone 6 IOS 10.3.2 (WHEN?)

### PR DESCRIPTION
**Pull request by jsbryans22**
Hi there,

When we will have a IOS 10.3.2 jailbreak?
Thank you for all your work, you are the best!

Regards

### CODE REVIEW

**Comment by andyvb1** [comment]
Stfu...

**Comment by andyvb1** [comment]
Close this rn

**Comment by andyvb1** [comment]
Pls

**Comment by jigsaw294** [comment]
I hope your iPhone updates on its own to iOS 11.0.3.

**Comment by rnavalgund** [comment]
Let your iPhone update to iOS 11.1 automatically while you are on wifi.
Please close this issue right now @jsbryans22 . This is stupid asking if the JB will support the particular firmware. Do some basic research before asking silly questions.

**Pull request closed without merging**
