### PR TITLE
triple_fetch speedup

### PR DESCRIPTION
**Pull request by MLGRadish**
Speeds up triple_fetch

### CODE REVIEW

**Comment by akasarx** [comment]
Nice!

**Comment by MrARM** [comment]
What did you do? I only see that you commented out a line yet to write it once again.

**Comment by akasarx** [comment]
Looks like it was already commented out. he just undid that :)

**Comment by iabem97** [comment]
this is unrelated. the call happens after triple fetch succeeds not while it is running. Thanks for the PR though.

**Pull request closed without merging**
