### PR TITLE
Fixed grammer in README.md

### PR DESCRIPTION
**Pull request by zpersondude9**

### CODE REVIEW

**Comment by jigsaw294** [comment]
lel @grammer >_>

**Comment by zpersondude9** [comment]
It hurt my body when I saw It, so I thought I'd make a quick pull request.

**Comment by jigsaw294** [comment]
It hurt my soul when I saw your "grammer".

**Comment by Grammer** [comment]
So you emailed me only to say someone wrote "grammer" instead of "grammar"
on repo I know nothing about? :D

16 окт. 2017 г. 17:40 пользователь "jigsaw294" <notifications@github.com>
написал:

**Comment by jigsaw294** [comment]
Vot blyat xaxaxa @Grammer

**Comment by zpersondude9** [comment]
FML I didn't see it

**Pull request closed without merging**
